version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shift
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata_migrate:/var/lib/postgresql/data
  migrator:
    image: ghcr.io/kislyuk/psql:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ../../packages/schema:/migrations:ro
      - ../../scripts:/scripts:ro
    entrypoint: ["/bin/sh", "/scripts/migrate.sh"]
volumes:
  pgdata_migrate:
