name: Deploy Staging Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pulumi
        run: ./scripts/ensure_pulumi.sh

      - name: Add Pulumi to PATH
        run: echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Deploy Staging Infrastructure
        run: |
          cd infra
          pulumi login --local
          pulumi stack select staging
          pulumi up --yes
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
